Css two column layout
jonathantrang/c0122-code-solutions pull request #28
Opened 2022-02-02 10:01 UTC by jonathantrang

![css-two-column](https://user-images.githubusercontent.com/96746037/152132618-1a285ab6-0565-4fa9-8644-f25c9dab0070.PNG)

2022-02-02 18:28 UTC, codingcodymiller requested changes
Hey Jonathan, all your headers are cased incorrectly, they should be all capital letters. Please revise and provide a new screenshot with your revision.

2022-02-03 00:00 UTC, jonathantrang commented
![Uploading Screen Shot 2022-02-02 at 3.15.09 PM.png…]()

2022-02-03 01:06 UTC, jonathantrang commented
<img width="923" alt="Screen Shot 2022-02-02 at 5 05 56 PM" src="https://user-images.githubusercontent.com/96746037/152264097-68c52362-9466-4310-8e07-c141508842b6.png">

2022-02-04 18:30 UTC, codingcodymiller approved these changes

2022-02-04 18:40 UTC, merged